# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('fichier', models.ImageField(upload_to='fichiers/')),
                ('sold', models.BooleanField(default='False')),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
            ],
            options={
                'verbose_name': 'Photographie',
                'verbose_name_plural': 'Photographies',
            },
        ),
    ]
