# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0002_pictures_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='price',
        ),
    ]
