# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0003_remove_pictures_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
