# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0008_auto_20160515_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='test',
        ),
    ]
