# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0009_remove_pictures_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galerie.themes'),
        ),
    ]
